spring:
  application:
    name: rebit

  datasource: # 데이터베이스 연결을 위한 설정
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # 데이터베이스 문법(방언) 설정
    open-in-view: false # 트랜잭션이 종료된 후 연결을 유지하지 않도록 설정
    defer-datasource-initialization: true # data.sql 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션
    hibernate:
      ddl-auto: create  # 테이블 생성 전략 설정

  sql:
    init:
      data-locations: classpath:data.sql  # 초기 데이터 설정
      mode: never # 애플리케이션 시작 시 SQL 스크립트 실행 여부 설정


# 카카오 소셜 로그인을 위해 사용하는 정보들 설정
oauth:
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    url:
      auth-url: ${OAUTH_KAKAO_AUTH_URL}
      api-url: ${OAUTH_KAKAO_API_URL}
      redirect-url: ${OAUTH_KAKAO_REDIRECT_URI}
      logout-redirect-url:  ${OAUTH_KAKAO_LOGOUT_REDIRECT_URI}


logging:
  level:
    org.springframework:
      transaction.interceptor: trace    # 트랜잭션 로그 설정

    p6spy: info # p6spy 로그 레벨 설정


# p6spy 로그 여부 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true
